### ISSUE TITLE
Impossible to setup linked filters in dashboards

### ISSUE THREAD

**Issue by michal-billtech** [flovouin/terraform-provider-metabase#53]
Metabase has a very useful feature called [linked filters](https://www.metabase.com/learn/dashboards/linking-filters), but it seems impossible to use it with this provider. I describe my attempts below:

Let's take a simplest possible dashboard resource with two parameters:

```terraform
resource "metabase_dashboard" "dashboard" {
  name        = "📈 Some great dashboard"
  description = "💡 With plenty of actionable stuff."

  parameters_json = jsonencode([
    {
      id                  = "12345678"
      name                = "foo"
      slug                = "foo"
      type                = "string/="
      sectionId           = "string"
    },
    {
      id                  = "23456789"
      name                = "bar"
      slug                = "bar"
      type                = "string/="
      sectionId           = "string"
    },
  ])

  cards_json = jsonencode([])
}
```

Usually when I want to use some new feature with this provider, I make changes in UI and run `terraform plan` to see what's missing in my code.
<img width="700" alt="image" src="https://github.com/flovouin/terraform-provider-metabase/assets/94702944/cb2fe689-1e3c-434a-b08e-fec185e691f5">

I run `terraform plan` and get:
![image](https://github.com/flovouin/terraform-provider-metabase/assets/94702944/cf575b57-8e58-497f-ae3c-45c9cb7f95ea)

Strange, let's take a look at network traffic: 
![image](https://github.com/flovouin/terraform-provider-metabase/assets/94702944/8f184624-53dd-4c0a-b135-17abf9744a9d)
The response for GET /api/dashboard/:id has included an appropriate field: `filteringParameters` but terraform provider doesn't pick it up.

Let's try to add it to the config:

```terraform
resource "metabase_dashboard" "dashboard" {
  name        = "📈 Some great dashboard"
  description = "💡 With plenty of actionable stuff."

  parameters_json = jsonencode([
    {
      id                  = "12345678"
      name                = "foo"
      slug                = "foo"
      type                = "string/="
      sectionId           = "string"
      filteringParameters = ["23456789"]
    },
    {
      id                  = "23456789"
      name                = "bar"
      slug                = "bar"
      type                = "string/="
      sectionId           = "string"
      filteringParameters = ["12345678"]
    },
  ])

  cards_json = jsonencode([])
}
```

and run `terraform apply`...
![image](https://github.com/flovouin/terraform-provider-metabase/assets/94702944/f5eb1c7f-241b-4468-a88c-7933049242d1)
Now it shows as a change (it shouldn't because this is already the state of the server).
After confirmation I get an error:
![image](https://github.com/flovouin/terraform-provider-metabase/assets/94702944/861362ff-427b-43ee-9b7a-d1c58459c94f)
Also network traffic inspections shows that the PUT request did not include the `filteringParameters` at all:
![image](https://github.com/flovouin/terraform-provider-metabase/assets/94702944/0191d4e5-7510-46df-82d1-57c7ed38b2a7)
which results in my changes made in UI being rolled back:
<img width="725" alt="image" src="https://github.com/flovouin/terraform-provider-metabase/assets/94702944/3e6c022d-0b70-4a4a-ab8a-d3babd12e530">

Seems to me that maybe there is some json processing in the provider both in parsing GET responses and in creating PUT requests which keeps only the known fields, `filteringParameters` not being among them. Please let me know if I'm missing something obvious here or just doing it wrong. Cheers!

**Comment by flovouin** [comment]
Hi @michal-billtech,

Thanks for reporting this. Indeed, the property was missing from the OpenAPI definition.
Unfortunately there is no official OpenAPI and I'm maintaining this one as I discover new features, which can cause issues like this one.

I've just release `v0.6.0`. Hopefully it solves your issue. Feel free to reopen if it doesn't.

**Comment by michal-billtech** [comment]
Damn, you're fast! Appreciate it! Thanks for the explanation, now that I know the cause, maybe I'll throw a PR next time I encounter anything missing in the OpenAPI.
